INSERT INTO preguntas (sentencia) VALUES ('Necesito encontrar el camino a una tienda que me ha recomendado un amigo. Yo haría:'),
                                         ('Un sitio web tiene un video que muestra cómo hacer un gráfico o tabla especial. Hay una persona hablando, algunas listas y palabras que describen qué hacer y algunos diagramas. Aprendería más de:'),
                                         ('Quiero obtener mas información sobre un viaje que voy a realizar. Me gustaría:'),
                                         ('A la hora de elegir una carrera o un área de estudio, estos aspectos son importantes para mí:'),
                                         ('Cuando estoy aprendiendo:'),
                                         ('Quiero ahorrar más dinero y decidir entre varias opciones. Yo haría lo siguiente:'),
                                         ('Quiero aprender a jugar a un nuevo juego de mesa o de cartas. Me gustaría:'),
                                         ('Tengo un problema cardíaco. Preferiría que el médico:'),
                                         ('Quiero aprender a hacer algo nuevo en la computadora. Me gustaría:'),
                                         ('Cuando aprendo por Internet, me gusta:'),
                                         ('Quiero saber más sobre un nuevo proyecto. Me gustaría preguntar:'),
                                         ('Quiero aprender a tomar mejores fotos. Yo haría lo siguiente:'),
                                         ('Prefiero un presentador o un maestro que utilice:'),
                                         ('He terminado una competencia o prueba y me gustaría recibir comentarios. Me gustaría recibir comentarios:'),
                                         ('Quiero obtener información sobre una casa o un departamento. Antes de visitarlo, me gustaría:'),
                                         ('Quiero armar una mesa de madera que vino en piezas. Aprendería mejor con:');