INSERT INTO alternativas (pregunta_id,alternativa_nombre,estilo_vark_id) VALUES (1,'Averiguaría dónde está la tienda en relación con algún lugar que conozco.',3),
                                                                                (1,'Le pediría a mi amigo que me dé las indicaciones.',2),
                                                                                (1,'Escribiría las direcciones de la calle que necesito recordar.',4),
                                                                                (1,'Usaría un mapa.',1),
                                                                                (2,'Viendo los diagramas.',1),
                                                                                (2,'Escuchando.',4),
                                                                                (2,'Leyendo las palabras.',2),
                                                                                (2,'Viendo las acciones.',3),
                                                                                (3,'Miraría los detalles sobre los puntos destacados y las actividades del tour.',3),
                                                                                (3,'Usaría un mapa para ver dónde están los lugares.',1),
                                                                                (3,'Leería sobre el tour en el itinerario.',4),
                                                                                (3,'Hablaría con la persona que organizó el tour o con otras personas que irán.',2),
                                                                                (4,'Aplicar mi conocimiento en situaciones reales.',3),
                                                                                (4,'Comunicarme con otros mediante discusión.',2),
                                                                                (4,'Trabajar con diseños, mapas o gráficos.',1),
                                                                                (4,'Usar bien las palabras en comunicaciones escritas.',4),
                                                                                (5,'Me gusta hablar sobre las cosas.',2),
                                                                                (5,'Veo patrones en las cosas.',1),
                                                                                (5,'Uso ejemplos y aplicaciones.',3),
                                                                                (5,'Leo libros, artículos y materiales.',4),
                                                                                (6,'Consideraría ejemplos de cada opción usando mi información financiera.',3),
                                                                                (6,'Leería un folleto impreso que describe las opciones en detalle.',4),
                                                                                (6,'Usaría gráficos que muestran diferentes opciones para diferentes períodos de tiempo.',1),
                                                                                (6,'Hablaría con un experto sobre las opciones.',2),
                                                                                (7,'Vería a otros jugar antes de unirme.',3),
                                                                                (7,'Escucharía a alguien explicarlo y haría preguntas.',2),
                                                                                (7,'Usaría los diagramas que explican las diversas etapas, movimientos y estrategias del juego.',1),
                                                                                (7,'Leería las instrucciones.',4),
                                                                                (8,'Me diera algo para leer y explicar qué estaba mal.',4),
                                                                                (8,'Usara un modelo de plástico para mostrarme qué estaba mal.',3),
                                                                                (8,'Describiera qué estaba mal.',2),
                                                                                (8,'Me mostrara un diagrama de qué estaba mal.',1),
                                                                                (9,'Leería las instrucciones escritas que venían con el programa.',4),
                                                                                (9,'Hablaría con personas que saben sobre el programa.',2),
                                                                                (9,'Empezaría a usarlo y aprendería por prueba y error.',3),
                                                                                (9,'Seguiría los diagramas de un libro.',1),
                                                                                (10,'Videos que muestran cómo hacer o crear cosas.',3),
                                                                                (10,'Características visuales y de diseño interesantes.',1),
                                                                                (10,'Descripciones escritas, listas y explicaciones interesantes.',4),
                                                                                (10,'Canales de audio donde puedo escuchar podcasts o entrevistas.',2),
                                                                                (11,'Diagramas que muestren las etapas del proyecto con gráficos de beneficios y costos.',1),
                                                                                (11,'Un informe escrito que describa las características principales del proyecto.',4),
                                                                                (11,'La oportunidad de discutir el proyecto.',2),
                                                                                (11,'Ejemplos de dónde se ha utilizado el proyecto con éxito.',3),
                                                                                (12,'Haría preguntas y hablaría sobre la cámara y sus características.',2),
                                                                                (12,'Usaría las instrucciones escritas sobre qué hacer.',4),
                                                                                (12,'Usaría diagramas que muestren la cámara y lo que hace cada parte.',1),
                                                                                (12,'Usaría ejemplos de fotos buenas y malas para mostrar cómo mejorarlas.',3),
                                                                                (13,'Demostraciones, modelos o sesiones prácticas.',3),
                                                                                (13,'Preguntas y respuestas, charlas, discusiones en grupo o conferencistas invitados.',2),
                                                                                (13,'Hojas de trabajo, libros o lecturas.',4),
                                                                                (13,'Diagramas, gráficos, mapas o gráficos.',1),
                                                                                (14,'Usando ejemplos de lo que hice.',3),
                                                                                (14,'Usando una descripción escrita de mis resultados.',4),
                                                                                (14,'De alguien que lo hable conmigo.',2),
                                                                                (14,'Usando gráficos que muestren lo que logré.',1),
                                                                                (15,'Ver un video de la propiedad.',3),
                                                                                (15,'Una discusión con el propietario.',2),
                                                                                (15,'Una descripción impresa de las habitaciones y características.',4),
                                                                                (15,'Un plano que muestre las habitaciones y un mapa de la zona.',1),
                                                                                (16,'Diagramas que muestren cada etapa del ensamblaje.',1),
                                                                                (16,'Consejos de alguien que ya lo haya hecho antes.',2),
                                                                                (16,'Instrucciones escritas que venían con las piezas de la mesa.',4),
                                                                                (16,'Viendo un video de una persona armando una mesa similar.',3);
