ALTER TABLE topics
    ADD COLUMN IF NOT EXISTS is_principal BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE topics
    ADD COLUMN IF NOT EXISTS is_basic BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE topics
    ADD COLUMN IF NOT EXISTS is_advanced BOOLEAN NOT NULL DEFAULT FALSE;

