server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: eureka-server # ¡Esto es la clave para Docker!
  client:
    register-with-eureka: false
    fetch-registry: false